#!/usr/bin/env python3
"""
cube.py — read, write, sample and measure .cube 3D LUTs. No I/O beyond files.

Two dialects live in Roman's collection and both must parse:
  * "resolve"    — TITLE "Generated by Resolve", space-separated, LF     (176 files)
  * "lut_editor" — no TITLE, TAB after LUT_3D_SIZE, CRLF, metadata in #  (9 files)
Hence every split is `line.split()` with no argument: it eats runs of spaces
AND tabs identically, so both dialects cost the same code.

AXIS ORDER — the expensive trap. In .cube the RED channel varies fastest:
    line i  ->  r = i % N,  g = (i // N) % N,  b = i // N**2
so `flat.reshape(N, N, N, 3)` is indexed [b, g, r], NOT [r, g, b]. Getting this
backwards yields a cube that is "almost right" and swaps channels in shadows —
not obvious by eye. selftest() asserts it; run it at import of any writer.

DOMAIN: not declared in a single file of the 203-cube collection, so the implied
0..1 is the norm here. A declared non-0..1 domain is kept and flagged, because
Premiere and ffmpeg disagree about what it means.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

VALID_SIZES = (17, 21, 25, 32, 33, 64, 65)


class CubeError(ValueError):
    """Malformed .cube — always carries the file path and what exactly is wrong."""


@dataclass
class Cube:
    size: int
    data: np.ndarray                      # (N, N, N, 3) float64, indexed [b, g, r]
    title: str | None = None
    domain_min: tuple = (0.0, 0.0, 0.0)
    domain_max: tuple = (1.0, 1.0, 1.0)
    domain_declared: bool = False
    comments: list[str] = field(default_factory=list)
    dialect: str = "resolve"
    path: Path | None = None

    @property
    def flat(self) -> np.ndarray:
        """(N**3, 3) in file order — red fastest."""
        return self.data.reshape(-1, 3)


# ---------------------------------------------------------------- parsing

def parse_cube(raw: bytes | str, path: Path | None = None) -> Cube:
    """Parse .cube text. Tolerates BOM, CRLF, CR, tabs, blank lines, trailing junk."""
    where = f"{path}: " if path else ""
    if isinstance(raw, bytes):
        raw = raw.decode("utf-8-sig", errors="replace")
    raw = raw.lstrip("﻿")

    size = None
    title = None
    dmin = dmax = None
    comments: list[str] = []
    vals: list[tuple[float, float, float]] = []
    saw_tab_header = False

    for line in re.split(r"\r\n|\r|\n", raw):
        s = line.strip()
        if not s:
            continue
        if s.startswith("#"):
            comments.append(s)
            continue

        upper = s.upper()
        if upper.startswith("LUT_3D_SIZE"):
            if "\t" in line:
                saw_tab_header = True
            parts = s.split()
            if len(parts) < 2:
                raise CubeError(f"{where}LUT_3D_SIZE without a value")
            try:
                size = int(parts[1])
            except ValueError as exc:
                raise CubeError(f"{where}LUT_3D_SIZE is not an integer: {parts[1]!r}") from exc
            continue
        if upper.startswith("LUT_1D_SIZE"):
            raise CubeError(f"{where}1D LUT — not supported, this pipeline is 3D only")
        if upper.startswith("TITLE"):
            m = re.search(r'"(.*)"', s)
            title = m.group(1) if m else s.split(None, 1)[1].strip() if len(s.split()) > 1 else None
            continue
        if upper.startswith("DOMAIN_MIN"):
            dmin = tuple(float(x) for x in s.split()[1:4])
            continue
        if upper.startswith("DOMAIN_MAX"):
            dmax = tuple(float(x) for x in s.split()[1:4])
            continue

        parts = s.split()
        if len(parts) < 3:
            continue
        try:
            vals.append((float(parts[0]), float(parts[1]), float(parts[2])))
        except ValueError:
            # Not a data row and not a keyword we know — ignore rather than die:
            # the collection has stray lines from three different generators.
            continue

    if size is None:
        raise CubeError(f"{where}no LUT_3D_SIZE")
    expected = size ** 3
    if len(vals) != expected:
        raise CubeError(f"{where}{len(vals)} data rows, expected {size}^3 = {expected}")

    data = np.asarray(vals, dtype=np.float64).reshape(size, size, size, 3)

    dialect = "resolve"
    if title is None and saw_tab_header:
        dialect = "lut_editor"
    elif title and "Insta360" in title:
        dialect = "insta360"
    elif title is None:
        dialect = "other"

    return Cube(
        size=size,
        data=data,
        title=title,
        domain_min=dmin or (0.0, 0.0, 0.0),
        domain_max=dmax or (1.0, 1.0, 1.0),
        domain_declared=bool(dmin or dmax),
        comments=comments,
        dialect=dialect,
        path=path,
    )


def load_cube(path: str | Path) -> Cube:
    path = Path(path)
    return parse_cube(path.read_bytes(), path=path)


def write_cube(cube: Cube, path: str | Path, title: str | None = None,
               comments: list[str] | None = None) -> Path:
    """Write canonical Resolve-dialect .cube: spaces, LF, 6 decimals."""
    path = Path(path)
    n = cube.size
    out = []
    for line in (comments or cube.comments):
        out.append(line if line.startswith("#") else f"# {line}")
    ttl = title if title is not None else cube.title
    if ttl:
        out.append(f'TITLE "{ttl}"')
    out.append(f"LUT_3D_SIZE {n}")
    if cube.domain_declared:
        out.append("DOMAIN_MIN " + " ".join(f"{v:.6f}" for v in cube.domain_min))
        out.append("DOMAIN_MAX " + " ".join(f"{v:.6f}" for v in cube.domain_max))
    out.append("")
    flat = cube.data.reshape(-1, 3)
    out.extend(f"{r:.6f} {g:.6f} {b:.6f}" for r, g, b in flat)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------- sampling

def grid(size: int) -> np.ndarray:
    """(size**3, 3) sample points in FILE order — red fastest. Feed to sample()."""
    ax = np.linspace(0.0, 1.0, size)
    b, g, r = np.meshgrid(ax, ax, ax, indexing="ij")
    return np.stack([r, g, b], axis=-1).reshape(-1, 3)


def sample(cube: Cube, pts: np.ndarray) -> np.ndarray:
    """Trilinear lookup. pts (..., 3) RGB in 0..1 -> same shape.

    Runtimes (ffmpeg, Lumetri) interpolate tetrahedrally; this is trilinear.
    That is fine for composing and for acceptance arithmetic as long as BOTH
    sides of a comparison use this same function — see compose acceptance.
    """
    shape = pts.shape
    p = np.clip(np.asarray(pts, dtype=np.float64).reshape(-1, 3), 0.0, 1.0)
    n = cube.size
    d = cube.data

    x = p * (n - 1)
    i0 = np.floor(x).astype(np.int32)
    i1 = np.minimum(i0 + 1, n - 1)
    f = x - i0
    r0, g0, b0 = i0[:, 0], i0[:, 1], i0[:, 2]
    r1, g1, b1 = i1[:, 0], i1[:, 1], i1[:, 2]
    fr, fg, fb = f[:, 0:1], f[:, 1:2], f[:, 2:3]

    c00 = d[b0, g0, r0] * (1 - fr) + d[b0, g0, r1] * fr
    c01 = d[b0, g1, r0] * (1 - fr) + d[b0, g1, r1] * fr
    c10 = d[b1, g0, r0] * (1 - fr) + d[b1, g0, r1] * fr
    c11 = d[b1, g1, r0] * (1 - fr) + d[b1, g1, r1] * fr
    c0 = c00 * (1 - fg) + c01 * fg
    c1 = c10 * (1 - fg) + c11 * fg
    return (c0 * (1 - fb) + c1 * fb).reshape(shape)


def identity(size: int) -> Cube:
    return Cube(size=size, data=grid(size).reshape(size, size, size, 3),
                title="identity", dialect="resolve")


# ---------------------------------------------------------------- metrics

def neutral_ramp(cube: Cube, steps: int = 65) -> tuple[np.ndarray, np.ndarray]:
    """Grey wedge in, wedge out. Returns (x (steps,), y (steps, 3))."""
    x = np.linspace(0.0, 1.0, steps)
    return x, sample(cube, np.repeat(x[:, None], 3, axis=1))


def measure(cube: Cube) -> dict:
    """Numbers that separate a develop LUT from a look.

    identity_rmse255 — how far the cube moves neutral at all. A log->709 develop
      MUST unpack the logarithm: S-Log3 encodes 18% grey near 0.41 and it has to
      land at 0.18, a 0.23 shift = 59/255 on that node alone. No look moves
      neutral like that; a look works on top of an already-normal picture.
    slope_mid       — mid-tone contrast gain, confirming signal only.
    neutral_drift255 — does the cube tint grey. A develop must not; a look may.
    black/white_share — where the cube crushes or blows the wedge by itself.
    """
    x, y = neutral_ramp(cube)
    ymean = y.mean(axis=1)
    lo, hi = sample(cube, np.array([[0.20] * 3, [0.60] * 3]))
    # Monotonicity as a MAGNITUDE, not a boolean. Real cubes wobble by a fraction of
    # a code value between nodes (measured: Canon Vision dips 0.59/255 once, the Apple
    # Log pre-LUT 0.53/255 once) — that is quantisation, not an inverted tone curve.
    # A genuinely flipped curve loses tens of code values, so report the number and
    # let the caller threshold it.
    dips = np.diff(ymean)
    dips = dips[dips < 0]
    return {
        "identity_rmse255": float(255.0 * np.sqrt(np.mean((ymean - x) ** 2))),
        "slope_mid": float((hi.mean() - lo.mean()) / 0.40),
        "neutral_drift255": float(255.0 * np.max(y.max(axis=1) - y.min(axis=1))),
        "black_share": float(np.mean(y.max(axis=1) <= 6 / 255)),
        "white_share": float(np.mean(y.min(axis=1) >= 250 / 255)),
        "dip_total255": float(-255.0 * dips.sum()) if dips.size else 0.0,
        "dip_max255": float(-255.0 * dips.min()) if dips.size else 0.0,
        "out_of_range": float(np.mean((cube.data < 0.0) | (cube.data > 1.0))),
        "value_max": float(cube.data.max()),
        "value_min": float(cube.data.min()),
    }


# ---------------------------------------------------------------- selftest

def selftest() -> None:
    """Assert red is the fast axis and sampling round-trips exactly on nodes."""
    n = 9
    ident = identity(n)
    got = sample(ident, grid(n))
    assert np.abs(got - grid(n)).max() < 1e-12, "identity cube must round-trip exactly"

    # A cube whose value encodes its own index proves which axis moves fastest.
    probe = np.zeros((n, n, n, 3))
    for b in range(n):
        for g in range(n):
            for r in range(n):
                probe[b, g, r] = (r / (n - 1), g / (n - 1), b / (n - 1))
    flat = probe.reshape(-1, 3)
    assert flat[1][0] > flat[0][0] and flat[1][1] == flat[0][1], \
        "red must be the fastest axis in file order"
    assert flat[n][1] > flat[0][1] and flat[n][0] == flat[0][0], \
        "green must be the second axis"


if __name__ == "__main__":
    selftest()
    print("cube.py selftest ok — red is the fast axis, identity round-trips")
