#!/usr/bin/env python3
"""
YTAI Folder Structure Creator

Usage:
    python create_folders.py -f "/path/to/new_folder"
    python create_folders.py -p "/path/to/new_folder"

Or simply copy the template folders:
    cp -r Type1_Footage "/path/to/20250125_Interview"
    cp -r Type2_Production "/path/to/YTRF01_My_Video"
"""

import os
import sys
import shutil
import argparse
import platform
import getpass
from datetime import datetime


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TYPE1_TEMPLATE = os.path.join(SCRIPT_DIR, "Type1_Footage")
TYPE2_TEMPLATE = os.path.join(SCRIPT_DIR, "Type2_Production")


def write_log(base_path: str, folder_type: str, folder_name: str) -> str:
    """Write detailed log file with timestamp"""
    log_dir = os.path.join(base_path, "99_Pipeline", "logs")
    os.makedirs(log_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    timestamp_readable = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_filename = f"{timestamp}_folder_created.log"
    log_path = os.path.join(log_dir, log_filename)
    
    log_content = f"""YTAI Folder Structure Log
{'='*60}

GENERAL INFO
------------
Type:       {folder_type}
Name:       {folder_name}
Created:    {timestamp_readable}
Path:       {base_path}

SYSTEM INFO
-----------
User:       {getpass.getuser()}
Machine:    {platform.node()}
OS:         {platform.system()} {platform.release()}
Python:     {platform.python_version()}

STRUCTURE CREATED
-----------------
📁 {folder_name}/
{chr(10).join(['   ' + line for line in get_tree(base_path)])}

NEXT STEPS
----------
"""
    
    if "Type 1" in folder_type:
        log_content += """1. Copy camera files to: 01_Source/video/
2. Copy audio files to:  01_Source/audio/
3. Run transcription → 02_Brief/transcription.xlsx
"""
    else:
        log_content += f"""1. Rename PROJECT_NAME.gdoc → {folder_name}.gdoc
2. Rename 01_Source/PROJECT_NAME.prproj → 01_Source/{folder_name}.prproj
3. Copy Type 1 footage folders to: 01_Source/
4. Add music/graphics to: 01_Source/assets/
5. Generate edit brief → 02_Brief/
"""
    
    log_content += f"""
{'='*60}
Log generated by YTAI Folder Structure Creator
"""
    
    with open(log_path, 'w') as f:
        f.write(log_content)
    
    return log_filename


def get_tree(path, prefix=""):
    """Get folder tree as list of strings"""
    items = []
    contents = sorted(os.listdir(path))
    # Filter out .gitkeep
    contents = [c for c in contents if c != '.gitkeep']
    
    for i, name in enumerate(contents):
        full_path = os.path.join(path, name)
        is_last = i == len(contents) - 1
        connector = "└── " if is_last else "├── "
        
        if os.path.isdir(full_path):
            items.append(f"{prefix}{connector}{name}/")
            extension = "    " if is_last else "│   "
            items.extend(get_tree(full_path, prefix + extension))
        else:
            items.append(f"{prefix}{connector}{name}")
    
    return items


def copy_template(template_path: str, dest_path: str, folder_type: str) -> None:
    """Copy template folder to destination"""
    folder_name = os.path.basename(dest_path)
    
    print(f"\n🎬 Creating {folder_type} structure...")
    print(f"📍 Path: {dest_path}\n")
    
    # Check if template exists
    if not os.path.exists(template_path):
        print(f"❌ Error: Template not found: {template_path}")
        sys.exit(1)
    
    # Copy template
    if os.path.exists(dest_path):
        print(f"📁 Folder exists, adding missing items...")
        for item in os.listdir(template_path):
            src = os.path.join(template_path, item)
            dst = os.path.join(dest_path, item)
            if not os.path.exists(dst):
                if os.path.isdir(src):
                    shutil.copytree(src, dst)
                else:
                    shutil.copy2(src, dst)
    else:
        shutil.copytree(template_path, dest_path)
    
    # Remove .gitkeep files
    for root, dirs, files in os.walk(dest_path):
        for f in files:
            if f == '.gitkeep':
                os.remove(os.path.join(root, f))
    
    # Print structure
    print(f"📁 {folder_name}/")
    for line in get_tree(dest_path):
        print(f"   {line}")
    
    # Write log
    log_filename = write_log(dest_path, folder_type, folder_name)
    
    # Next steps
    if "Type 1" in folder_type:
        print(f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Type 1 (Footage) ready!

📋 Next steps:
   1. Copy camera files to: 01_Source/video/
   2. Copy audio files to:  01_Source/audio/
   3. Run transcription → 02_Brief/transcription.xlsx

📝 Log: 99_Pipeline/logs/{log_filename}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")
    else:
        print(f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Type 2 (Production) ready!

📋 Next steps:
   1. Rename PROJECT_NAME.gdoc → {folder_name}.gdoc
   2. Rename 01_Source/PROJECT_NAME.prproj → 01_Source/{folder_name}.prproj
   3. Copy Type 1 footage folders to: 01_Source/
   4. Add music/graphics to: 01_Source/assets/
   5. Generate edit brief → 02_Brief/

📝 Log: 99_Pipeline/logs/{log_filename}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")


def main():
    parser = argparse.ArgumentParser(
        description="YTAI Folder Structure Creator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

USAGE (Script):
  python create_folders.py -f "/path/to/folder"    # Type 1: Footage
  python create_folders.py -p "/path/to/folder"    # Type 2: Production

USAGE (Manual copy):
  cp -r Type1_Footage "/path/to/20250125_Interview"
  cp -r Type2_Production "/path/to/YTRF01_My_Video"

TYPE 1 (Footage) — Single shooting day:
  01_Source/video/    Camera files
  01_Source/audio/    External audio
  02_Brief/           Transcription & analysis
  03_Exports/         Test exports
  99_Pipeline/logs/   System logs

TYPE 2 (Production) — Full project:
  PROJECT_NAME.gdoc   Google Doc link (rename to your project)
  01_Source/          Footage + assets + PROJECT_NAME.prproj
  02_Brief/           Edit brief, XML, chapters
  03_Exports/         Rendered videos
  04_Thumbnail/       Thumbnail project
  YouTube/            Final files for upload
  99_Pipeline/logs/   System logs

TEMPLATES LOCATION:
  {templates_dir}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        """.format(templates_dir=SCRIPT_DIR)
    )
    
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-f", "--footage", action="store_true", help="Type 1: Footage (single shooting day)")
    group.add_argument("-p", "--production", action="store_true", help="Type 2: Production (full project)")
    
    parser.add_argument("path", help="Path to create folder")
    
    args = parser.parse_args()
    
    # Clean path
    clean_path = args.path.strip("'\"")
    base_path = os.path.abspath(clean_path)
    
    if args.footage:
        copy_template(TYPE1_TEMPLATE, base_path, "Type 1 (Footage)")
    else:
        copy_template(TYPE2_TEMPLATE, base_path, "Type 2 (Production)")


if __name__ == "__main__":
    main()
